### ISSUE TITLE
Complete milestone p3.4.0-v0.1.0 and submit to DefinitelyTyped

### ISSUE THREAD

**Issue by AGBrown** [AGBrown/pouchdb.d.ts#14]
Needs:
- [ ] Complete items in [milestones/p3.4.0-v0.1.0](https://github.com/AGBrown/pouchdb.d.ts/milestones/p3.4.0-v0.1.0)
- [ ] Review pouchdb versions. `p3.4.0-v0.1.0` should correspond to `v3.4.0` - any new features for later pouchdb versions should be appropriately branched, labelled, versioned in this repo
- [ ] Review DefinitelyTyped for recent changes to the [DT Contribution guide](http://definitelytyped.org/guides/contributing.html)
- [ ] Create `v3.4.0` branch from `master`
- [ ] Create `v3.4.0-v0.1.0` tag on `v3.4.0` branch
- [ ] Create release with the appropriate file and folder structure for DefinitelyTyped and create PR through [DefinitelyTyped-ABContrib](https://github.com/AGBrown/DefinitelyTyped-ABContrib) relating to borisyankov/DefinitelyTyped#4328
- [ ] Update borisyankov/DefinitelyTyped#4328 with relevant info
- [ ] Advertise release
